### ISSUE TITLE
Unable to import package via NuGet

### ISSUE THREAD

**Issue by GregWhiteDBA** [bt-skyrise/PrtgSensorSharp#1]
Installing 'PrtgSensorSharp 1.0.8'.
Successfully installed 'PrtgSensorSharp 1.0.8'.
Adding 'PrtgSensorSharp 1.0.8' to PRTG AG Monitor.
Uninstalling 'PrtgSensorSharp 1.0.8'.
Successfully uninstalled 'PrtgSensorSharp 1.0.8'.
Install failed. Rolling back...
Could not install package 'PrtgSensorSharp 1.0.8'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by redss** [comment]
Hello Greg,

PrtgSensorSharp is built against .NET Framework v4.5.2, but it seems you are using Framework v4.0. Unfortunately, I am not planning to introduce building against multiple Framework versions at the moment. Your best option would be to upgrade to newer Framework, or create your own PrtgSensorSharp build, which targets v.4.0.

**Comment by GregWhiteDBA** [comment]
Excellent, thanks I will take a look at this. Also assume you use vs 2015. I'm using 2013 and having issues with  building. Not entirely sure where to go next (apologies for the rookie question)

On 8 Jul 2016, at 18:49, Ryszard Tarajkowski <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello Greg,

PrtgSensorSharp is built against .NET Framework v4.5.2, but it seems you are using Framework v4.0. Unfortunately, I am not planning to introduce building against multiple Framework versions at the moment. Your best option would be to upgrade to newer Framework, or create your own PrtgSensorSharp build, which targets v.4.0.

## 

You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHubhttps://github.com/bt-skyrise/PrtgSensorSharp/issues/1#issuecomment-231426433, or mute the threadhttps://github.com/notifications/unsubscribe/AQiGoK8xDgWpR75441WExLQR1DrgxNwfks5qTo2OgaJpZM4JH_en.

Greg White
This electronic mail and any attachments (email) has been sent by Integrated Care 24 Ltd or IC24 (formerly SEHL) and is confidential and may be legally privileged. It is intended for the sole use of the named individual(s) to whom it has been addressed. If you are not the intended recipient please do not disclose, distribute, copy, use or act upon it. Please contact IC24 quoting the name of the sender and the addressee, then delete from your system. We apologise for any inconvenience caused. WARNING: whilst IC24 has taken precautions to ensure that no viruses are present, the recipient should check this email for viruses. IC24 does not accept any responsibility for viruses once this email has been transmitted. IC24 is registered in England and Wales. Registered number: 3193182. Registered office: Kingston House, The Long Barrow, Orbital Park. Ashford. Kent TN24 0GP. Tel: 01233 505450 Fax: 01233 504052

**Comment by redss** [comment]
I believe you can use .NET 4.5 and newer on Visual Studio 2013. Take a look at this:

http://stackoverflow.com/a/31836150/5210564

This explains how to use .NET 4.6 on Visual Studio 2013, but I guess it will be similar for .NET 4.5. Hope it helps!

**Comment by GregWhiteDBA** [comment]
Excellent, thank you!

On 8 Jul 2016, at 19:25, Ryszard Tarajkowski <notifications@github.com<mailto:notifications@github.com>> wrote:

I believe you can use .NET 4.5 and newer on Visual Studio 2013. Take a look at this:

http://stackoverflow.com/a/31836150/5210564

This explains how to use .NET 4.6 on Visual Studio 2013, but I guess it will be similar for .NET 4.5. Hope it helps!

## 

You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHubhttps://github.com/bt-skyrise/PrtgSensorSharp/issues/1#issuecomment-231435734, or mute the threadhttps://github.com/notifications/unsubscribe/AQiGoKIPVOs-qCuwMVnlQS5gGZRJiP8-ks5qTpXdgaJpZM4JH_en.

Greg White
This electronic mail and any attachments (email) has been sent by Integrated Care 24 Ltd or IC24 (formerly SEHL) and is confidential and may be legally privileged. It is intended for the sole use of the named individual(s) to whom it has been addressed. If you are not the intended recipient please do not disclose, distribute, copy, use or act upon it. Please contact IC24 quoting the name of the sender and the addressee, then delete from your system. We apologise for any inconvenience caused. WARNING: whilst IC24 has taken precautions to ensure that no viruses are present, the recipient should check this email for viruses. IC24 does not accept any responsibility for viruses once this email has been transmitted. IC24 is registered in England and Wales. Registered number: 3193182. Registered office: Kingston House, The Long Barrow, Orbital Park. Ashford. Kent TN24 0GP. Tel: 01233 505450 Fax: 01233 504052
