### ISSUE TITLE
ptrgResult values as string?

### ISSUE THREAD

**Issue by GregWhiteDBA** [bt-skyrise/PrtgSensorSharp#2]
looking to display strings in the value is the possible, cannot work it out.

```
 PrtgExeScriptAdvanced.Run(()
                    =>
                    {
                        return PrtgReport.Successful(new[]
        {
            new PrtgResult("Primary SQL AG Name", servername),
            new PrtgResult("Number of active users", 1)
        });
                    });
```

string not assignable to parameter type, reason for string output is that I want to alert if the primary sql server changes i.e. a fail-over occurred.

**Comment by GregWhiteDBA** [comment]
closing as this is a limitation of PRTG

**Comment by redss** [comment]
As an alternative, you could return [additional message](https://github.com/bt-skyrise/PrtgSensorSharp/blob/master/source/PrtgSensorSharp.Tests/PrtgReportTests.cs#L31).
