### ISSUE TITLE
Response Not Wellformed

### ISSUE THREAD

**Issue by smlemmon** [bt-skyrise/PrtgSensorSharp#4]
Hi, I have just tried creating a small project using the nuget package today and I got the following response back when trying to test it. I assume I am doing something stupid. 

Please could you advise.

Many thanks in advance.

Simon
![prtg](https://user-images.githubusercontent.com/3618081/30911293-fb498eca-a37f-11e7-8810-0c5462ed8016.png)

**Comment by redss** [comment]
Hello Simon,

Your sensor's output looks ok. My guess is that in PRTG you've created a _EXE/Script_ type of sensor instead of _EXE/Script Advanced_ sensor. PrtgSensorSharp works only with _EXE/Script Advanced_. Please check this and let me know if it worked.

Best regards,
Ryszard
